### ISSUE TITLE
Add the option to disable automatic Pins

### ISSUE THREAD

**Issue by DrruuEU** [Nercus/MapPinEnhanced#31]
Hi there,

it would be great to implement an option to disable automatically set map pins.
As handy as it can be, instead of disabling them one by one each day if not needed, it would be great to have an option to disable this.

**Comment by Nercus** [comment]
Hey @DrruuEU 
I don't fully understand your request :)
If pins are automatically placed when opening the world map, that **was** caused by the addon Plumber and was fixed a couple of days ago.
If you just get pins that show up, you might want to check other addons. Map Pin Enhanced is just "listening" to the ingame event of the user waypoint. So if other addons place it Map Pin Enhanced will detect it.
If it's none of these things please elaborate further!

**Comment by DrruuEU** [comment]
Hi @Nercus ,
it seems like I was a bit too fast with reporting then.
Sorry for misunderstanding, I think it was the Plumber Issue you described after all, at least the 'problem' didn't occur today.
Thank you for your quick reply and working on such a convenient addon! :)

Best regards
