### ISSUE TITLE
MPE fails with error when copying character name with special characters from guild interface. 

### ISSUE THREAD

**Issue by Jahfry** [Nercus/MapPinEnhanced#33]
**Describe the bug**

**To Reproduce**

1. Install MPE
2. Go to Guild roster to copy the name of a guild member (in this case 'Réb', accented e may be important) ... right-click in roster to get the "copy" option. 
3. Get the error shown below and have to disable MPE to copy the player's name from the roster
4. Re-enable MPE and reload (see NOTE)

NOTE: I've had this error occur a few times now (same player, it's our GM, and I need to copy the name to send mail). However, just now when I re-enabled and reloaded I did not get the error on trying to reproduce. I exited the game completely (including B.net) and the error did not re-occur. 

Lack of reproduction sucks, but, as I've had it come up before I'll file this and post again next time it comes up. If I don't post in 3 weeks consider it to have fixed itself. 

**Expected behavior**

Guild member's name copies without interacting with MPE. 

**Screenshots**

**Do you have an error log of what happened?** (BugSack&Buggrabber or `/console scriptErrors 1`)

```plaintext
1x [ADDON_ACTION_FORBIDDEN] AddOn 'MapPinEnhanced' tried to call the protected function 'CopyToClipboard()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CopyToClipboard'
[string "@Blizzard_UnitPopupShared/UnitPopupSharedButtonMixins.lua"]:1337: in function <...zard_UnitPopupShared/UnitPopupSharedButtonMixins.lua:1336>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:868: in function `Pick'
[string "@Blizzard_Menu/MenuTemplates.lua"]:74: in function <Blizzard_Menu/MenuTemplates.lua:68>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}
```

**Did you try disabling all other addons? (Only MapPinEnhanced enabled)**

No as the reproduction went away. 

**Was it working in a previous version?**

The error has happened sporadically (every couple of weeks when I need to sent this player mail) since I started using MPE.

**Comment by Nercus** [comment]
Hey @Jahfry 

thanks for reporting the issue. That is a taint error. This means an addon is using a function it shouldn't use (during combat or in general). Because that system is pretty buggy it sometimes shows the incorrect addon in the shown error. So that could mean that another addon is triggering it, but Map Pin Enhanced is "blamed" for it.
Try the following please:
1. Enable taint logging with: `/console taintLog 1`
2. Try to reproduce the issue
3. Inside the wow folder go into `_retail_/Logs` and please provide the "taint.log" file.

This should help me to pin point the exact cause. Thanks in advance!

**Comment by Nercus** [comment]
Not enough information!
